import type { Celebration } from "../types";
import type { FixedCelebration } from "./sanctorale";

function feast(name: string): Celebration {
  return { name, rank: "feast", isSolemnity: false, source: "curated" };
}

/**
 * The 1962 Sanctorale's Saint-of-the-Day list: which saint (or other fixed
 * commemoration) falls on each MM-DD, for dates not already covered by a
 * major solemnity in sanctorale.ts. Sourced from the Missale Meum API
 * (missalemeum.com, MIT licensed), which computes real 1962 rubrics —
 * reconstructed here as a year-independent list by sampling many years and
 * combining primary, commemorated, and displaced entries, since a saint's
 * precedence (and occasionally date, when it collides with a Sunday) shifts
 * with where a given year's Easter falls. This calendar is a closed
 * historical document that will not change, so this list needs no further
 * updates.
 */
export const saintsSeed: FixedCelebration[] = [
  { monthDay: "01-05", celebration: feast("St. Telesphorus Pope and Martyr") },
  { monthDay: "01-13", celebration: feast("Commemoration of the Baptism of the Lord") },
  { monthDay: "01-14", celebration: feast("St. Hilary") },
  { monthDay: "01-15", celebration: feast("St. Paul, the First Hermit") },
  { monthDay: "01-16", celebration: feast("St. Marcellus I") },
  { monthDay: "01-17", celebration: feast("St. Anthony") },
  { monthDay: "01-18", celebration: feast("St. Prisca") },
  { monthDay: "01-19", celebration: feast("Sts. Marius, Martha, Audifax & Abachum") },
  { monthDay: "01-20", celebration: feast("Sts. Fabian & Sebastian") },
  { monthDay: "01-21", celebration: feast("St. Agnes") },
  { monthDay: "01-22", celebration: feast("Sts. Vincent & Anastasius") },
  { monthDay: "01-23", celebration: feast("St. Raymond of Peñafort") },
  { monthDay: "01-24", celebration: feast("St. Timothy") },
  { monthDay: "01-25", celebration: feast("Conversion of St. Paul") },
  { monthDay: "01-26", celebration: feast("St. Polycarp") },
  { monthDay: "01-27", celebration: feast("St. John Chrysostom") },
  { monthDay: "01-28", celebration: feast("St. Peter Nolasco") },
  { monthDay: "01-29", celebration: feast("St. Francis de Sales") },
  { monthDay: "01-30", celebration: feast("St. Martina") },
  { monthDay: "01-31", celebration: feast("St. John Bosco") },
  { monthDay: "02-01", celebration: feast("St. Ignatius of Antioch") },
  { monthDay: "02-02", celebration: feast("Purification of the Blessed Virgin Mary") },
  { monthDay: "02-03", celebration: feast("St. Blaise") },
  { monthDay: "02-04", celebration: feast("St. Andrew Corsini") },
  { monthDay: "02-05", celebration: feast("St. Agatha") },
  { monthDay: "02-06", celebration: feast("St. Titus") },
  { monthDay: "02-07", celebration: feast("St. Romuald") },
  { monthDay: "02-08", celebration: feast("St. John of Matha") },
  { monthDay: "02-09", celebration: feast("St. Cyril of Alexandria") },
  { monthDay: "02-10", celebration: feast("St. Scholastica") },
  { monthDay: "02-11", celebration: feast("Our Lady of Lourdes") },
  { monthDay: "02-12", celebration: feast("Seven Holy Servite Founders") },
  { monthDay: "02-14", celebration: feast("St. Valentine") },
  { monthDay: "02-15", celebration: feast("Sts. Faustinus & Jovita") },
  { monthDay: "02-18", celebration: feast("St. Simeon") },
  { monthDay: "02-22", celebration: feast("Chair of St. Peter") },
  { monthDay: "02-23", celebration: feast("St. Peter Damien") },
  { monthDay: "02-24", celebration: feast("St. Matthias") },
  { monthDay: "02-27", celebration: feast("St. Gabriel of Our Lady of Sorrows") },
  { monthDay: "03-04", celebration: feast("St. Casimir") },
  { monthDay: "03-06", celebration: feast("Sts. Felicitas & Perpetua") },
  { monthDay: "03-07", celebration: feast("St. Thomas Aquinas") },
  { monthDay: "03-08", celebration: feast("St. John of God") },
  { monthDay: "03-09", celebration: feast("St. Frances Rome") },
  { monthDay: "03-10", celebration: feast("Forty Holy Martyrs of Sebaste") },
  { monthDay: "03-12", celebration: feast("St. Gregory the Great") },
  { monthDay: "03-17", celebration: feast("St. Patrick") },
  { monthDay: "03-18", celebration: feast("St. Cyril of Jerusalem") },
  { monthDay: "03-21", celebration: feast("St. Benedict") },
  { monthDay: "03-24", celebration: feast("St. Gabriel the Archangel") },
  { monthDay: "03-27", celebration: feast("St. John Damascene") },
  { monthDay: "03-28", celebration: feast("St. John of Capistrano") },
  { monthDay: "04-02", celebration: feast("St. Francis of Paola") },
  { monthDay: "04-04", celebration: feast("St. Isidore of Seville") },
  { monthDay: "04-05", celebration: feast("St. Vincent Ferrer") },
  { monthDay: "04-11", celebration: feast("St. Leo the Great") },
  { monthDay: "04-13", celebration: feast("St. Hermenegild") },
  { monthDay: "04-14", celebration: feast("St. Justin") },
  { monthDay: "04-17", celebration: feast("St. Anicetus") },
  { monthDay: "04-21", celebration: feast("St. Anselm") },
  { monthDay: "04-22", celebration: feast("Sts. Soter & Caius") },
  { monthDay: "04-23", celebration: feast("St. George") },
  { monthDay: "04-24", celebration: feast("St. Fidelis of Sigmaringen") },
  { monthDay: "04-25", celebration: feast("St. Mark") },
  { monthDay: "04-26", celebration: feast("Sts. Cletus & Marcellinus") },
  { monthDay: "04-27", celebration: feast("St. Peter Canisius") },
  { monthDay: "04-28", celebration: feast("St. Paul of the Cross") },
  { monthDay: "04-29", celebration: feast("St. Peter of Verona") },
  { monthDay: "04-30", celebration: feast("St. Catherine of Siena") },
  { monthDay: "05-01", celebration: feast("St. Joseph the Workman") },
  { monthDay: "05-02", celebration: feast("St. Athanasius") },
  { monthDay: "05-03", celebration: feast("Sts. Alexander & Companions") },
  { monthDay: "05-04", celebration: feast("St. Monica") },
  { monthDay: "05-05", celebration: feast("St. Pius V") },
  { monthDay: "05-07", celebration: feast("St. Stanislaus") },
  { monthDay: "05-09", celebration: feast("St. Gregory of Nazianzen") },
  { monthDay: "05-10", celebration: feast("St. Antoninus") },
  { monthDay: "05-11", celebration: feast("Sts. Philip & James") },
  { monthDay: "05-12", celebration: feast("Sts. Nereus, Achilleus, Domitilla, & Pancras") },
  { monthDay: "05-13", celebration: feast("St. Robert Bellarmine") },
  { monthDay: "05-14", celebration: feast("St. Boniface") },
  { monthDay: "05-15", celebration: feast("St. John Baptist de la Salle") },
  { monthDay: "05-16", celebration: feast("St. Ubaldus") },
  { monthDay: "05-17", celebration: feast("St. Paschal Baylon") },
  { monthDay: "05-18", celebration: feast("St. Venantius") },
  { monthDay: "05-19", celebration: feast("St. Peter Celestine") },
  { monthDay: "05-20", celebration: feast("St. Bernardine of Siena") },
  { monthDay: "05-25", celebration: feast("St. Gregory VII") },
  { monthDay: "05-26", celebration: feast("St. Philip Neri") },
  { monthDay: "05-27", celebration: feast("St. Bede the Venerable") },
  { monthDay: "05-28", celebration: feast("St. Augustine of Canterbury") },
  { monthDay: "05-29", celebration: feast("St. Mary Magdalene de Pazzi") },
  { monthDay: "05-30", celebration: feast("St. Felix I") },
  { monthDay: "05-31", celebration: feast("Queenship of the Blessed Virgin Mary") },
  { monthDay: "06-01", celebration: feast("St. Angela Merici") },
  { monthDay: "06-02", celebration: feast("Sts. Marcellinus, Peter, & Erasmus") },
  { monthDay: "06-04", celebration: feast("St. Francis Caracciolo") },
  { monthDay: "06-05", celebration: feast("St. Boniface") },
  { monthDay: "06-06", celebration: feast("St. Norbert") },
  { monthDay: "06-09", celebration: feast("Sts. Primus & Felicianus") },
  { monthDay: "06-10", celebration: feast("St. Margaret of Scotland") },
  { monthDay: "06-11", celebration: feast("St. Barnabas") },
  { monthDay: "06-12", celebration: feast("St. John of San Fecundo") },
  { monthDay: "06-13", celebration: feast("St. Anthony of Padua") },
  { monthDay: "06-14", celebration: feast("St. Basil the Great") },
  { monthDay: "06-15", celebration: feast("St. Vitus") },
  { monthDay: "06-17", celebration: feast("St. Gregory Barbarigo") },
  { monthDay: "06-18", celebration: feast("St. Ephrem of Syria") },
  { monthDay: "06-19", celebration: feast("St. Julia of Falconieri") },
  { monthDay: "06-20", celebration: feast("St. Silverius") },
  { monthDay: "06-21", celebration: feast("St. Aloysius Gongzaga") },
  { monthDay: "06-22", celebration: feast("St. Paulinus of Nola") },
  { monthDay: "06-23", celebration: feast("Vigil of the Nativity of St. John the Baptist") },
  { monthDay: "06-25", celebration: feast("St. William") },
  { monthDay: "06-26", celebration: feast("Sts. John & Paul") },
  { monthDay: "06-28", celebration: feast("Vigil of Sts. Peter & Paul") },
  { monthDay: "06-30", celebration: feast("In Commemoratione Sancti Pauli Apostoli") },
  { monthDay: "07-01", celebration: feast("The Precious Blood of Our Lord Jesus Christ") },
  { monthDay: "07-02", celebration: feast("Visitation of the Blessed Virgin Mary") },
  { monthDay: "07-03", celebration: feast("St. Irenaeus") },
  { monthDay: "07-05", celebration: feast("St. Anthony Mary Zaccariah") },
  { monthDay: "07-06", celebration: feast("St. Maria Goretti") },
  { monthDay: "07-07", celebration: feast("Sts. Cyril & Methodius") },
  { monthDay: "07-08", celebration: feast("St. Elizabeth of Portugal") },
  { monthDay: "07-10", celebration: feast("Seven Holy Brothers and Sts. Rufina & Secunda") },
  { monthDay: "07-11", celebration: feast("St. Pius I") },
  { monthDay: "07-12", celebration: feast("St. John Gualbert") },
  { monthDay: "07-14", celebration: feast("St. Bonaventure") },
  { monthDay: "07-15", celebration: feast("St. Henry the Emperor") },
  { monthDay: "07-16", celebration: feast("Our Lady of Mt. Carmel") },
  { monthDay: "07-17", celebration: feast("St. Alexis") },
  { monthDay: "07-18", celebration: feast("Camillus de Lellis") },
  { monthDay: "07-19", celebration: feast("St. Vincent de Paul") },
  { monthDay: "07-20", celebration: feast("St. Jerome Emiliani") },
  { monthDay: "07-21", celebration: feast("St. Laurence of Brindisi") },
  { monthDay: "07-22", celebration: feast("St. Mary Magdalene") },
  { monthDay: "07-23", celebration: feast("St. Apollinaris") },
  { monthDay: "07-24", celebration: feast("St. Christina") },
  { monthDay: "07-25", celebration: feast("St. James the Greater") },
  { monthDay: "07-26", celebration: feast("St. Anne, Mother of the Blessed Virgin") },
  { monthDay: "07-27", celebration: feast("St. Pantaleon") },
  { monthDay: "07-28", celebration: feast("Sts. Nazarius & Celsus, St. Victor I & St. Innocent I") },
  { monthDay: "07-29", celebration: feast("St. Martha") },
  { monthDay: "07-30", celebration: feast("Sts. Abdon & Sennen") },
  { monthDay: "07-31", celebration: feast("St. Ignatius Loyola") },
  { monthDay: "08-01", celebration: feast("Holy Machabees") },
  { monthDay: "08-02", celebration: feast("St. Alphonsus Liguori") },
  { monthDay: "08-04", celebration: feast("St. Dominic") },
  { monthDay: "08-05", celebration: feast("Dedication of the Basilica of St. Mary Major") },
  { monthDay: "08-06", celebration: feast("Transfiguration of Our Lord") },
  { monthDay: "08-07", celebration: feast("St. Cajetan") },
  { monthDay: "08-08", celebration: feast("St. John Mary Vianney") },
  { monthDay: "08-09", celebration: feast("Vigil of St. Lawrence") },
  { monthDay: "08-10", celebration: feast("St. Lawrence") },
  { monthDay: "08-11", celebration: feast("Sts. Tiburtius & Susanna") },
  { monthDay: "08-12", celebration: feast("St. Clare") },
  { monthDay: "08-13", celebration: feast("Sts. Hippolytus & Cassian") },
  { monthDay: "08-14", celebration: feast("Vigil of the Assumption") },
  { monthDay: "08-16", celebration: feast("St. Joachim, Father of the Blessed Virgin") },
  { monthDay: "08-17", celebration: feast("St. Hyacinth") },
  { monthDay: "08-18", celebration: feast("St. Agapitus") },
  { monthDay: "08-19", celebration: feast("St. John Eudes") },
  { monthDay: "08-20", celebration: feast("St. Bernard of Clairvaux") },
  { monthDay: "08-21", celebration: feast("St. Jane Frances de Chantal") },
  { monthDay: "08-22", celebration: feast("Immaculate Heart of Mary") },
  { monthDay: "08-23", celebration: feast("St. Philip Benizi") },
  { monthDay: "08-24", celebration: feast("St. Bartholomew") },
  { monthDay: "08-25", celebration: feast("St. Louis IX") },
  { monthDay: "08-26", celebration: feast("St. Zephyrinus") },
  { monthDay: "08-27", celebration: feast("St. Joseph Calasance") },
  { monthDay: "08-28", celebration: feast("St. Augustine") },
  { monthDay: "08-29", celebration: feast("Beheading of St. John the Baptist") },
  { monthDay: "08-30", celebration: feast("St. Rose of Lima") },
  { monthDay: "08-31", celebration: feast("St. Raymond Nonnatus") },
  { monthDay: "09-01", celebration: feast("St. Giles") },
  { monthDay: "09-02", celebration: feast("St. Stephen of Hungary") },
  { monthDay: "09-03", celebration: feast("St. Pius X") },
  { monthDay: "09-05", celebration: feast("St. Lawrence Justinian") },
  { monthDay: "09-08", celebration: feast("Nativity of the Blessed Virgin Mary") },
  { monthDay: "09-09", celebration: feast("St. Gorgonius") },
  { monthDay: "09-10", celebration: feast("St. Nicholas of Tolentino") },
  { monthDay: "09-11", celebration: feast("Sts. Protus & Hyacinth") },
  { monthDay: "09-12", celebration: feast("Most Holy Name of Mary") },
  { monthDay: "09-14", celebration: feast("Exaltation of the Holy Cross") },
  { monthDay: "09-15", celebration: feast("Seven Sorrows of the Blessed Virgin Mary") },
  { monthDay: "09-16", celebration: feast("Sts. Cornelius & Cyprian") },
  { monthDay: "09-17", celebration: feast("Stigmata of St. Francis") },
  { monthDay: "09-18", celebration: feast("St. Joseph of Cupertino") },
  { monthDay: "09-19", celebration: feast("St. Januarius & Companions") },
  { monthDay: "09-20", celebration: feast("Sts. Eustace & Companions") },
  { monthDay: "09-21", celebration: feast("St. Matthew") },
  { monthDay: "09-22", celebration: feast("St. Thomas of Villanova") },
  { monthDay: "09-23", celebration: feast("St. Linus") },
  { monthDay: "09-24", celebration: feast("Our Lady of Ransom") },
  { monthDay: "09-26", celebration: feast("Sts. Cyprian & Justina") },
  { monthDay: "09-27", celebration: feast("Sts. Cosmas & Damian") },
  { monthDay: "09-28", celebration: feast("St. Wenceslaus") },
  { monthDay: "09-29", celebration: feast("Dedication of St. Michael the Archangel") },
  { monthDay: "09-30", celebration: feast("St. Jerome") },
  { monthDay: "10-01", celebration: feast("St. Remigius") },
  { monthDay: "10-02", celebration: feast("Holy Guardian Angels") },
  { monthDay: "10-03", celebration: feast("St. Theresa of the Infant Jesus") },
  { monthDay: "10-04", celebration: feast("St. Francis of Assisi") },
  { monthDay: "10-05", celebration: feast("St. Placid & Companions") },
  { monthDay: "10-06", celebration: feast("St. Bruno") },
  { monthDay: "10-07", celebration: feast("Our Lady of the Rosary") },
  { monthDay: "10-08", celebration: feast("St. Bridget of Sweden") },
  { monthDay: "10-09", celebration: feast("St. John Leonardi") },
  { monthDay: "10-10", celebration: feast("St. Francis Borgia") },
  { monthDay: "10-11", celebration: feast("Maternity of the Blessed Virgin Mary") },
  { monthDay: "10-13", celebration: feast("St. Edward") },
  { monthDay: "10-14", celebration: feast("St. Callistus I") },
  { monthDay: "10-15", celebration: feast("St. Teresa of Avila") },
  { monthDay: "10-16", celebration: feast("St. Hedwig") },
  { monthDay: "10-17", celebration: feast("St. Margaret Mary Alacoque") },
  { monthDay: "10-18", celebration: feast("St. Luke the Evangelist") },
  { monthDay: "10-19", celebration: feast("St. Peter of Alcantara") },
  { monthDay: "10-20", celebration: feast("St. John Cantius") },
  { monthDay: "10-21", celebration: feast("St. Hilarion") },
  { monthDay: "10-23", celebration: feast("St. Anthony Mary Claret") },
  { monthDay: "10-24", celebration: feast("St. Raphael the Archangel") },
  { monthDay: "10-25", celebration: feast("Sts. Chrysanthus & Daria") },
  { monthDay: "10-26", celebration: feast("St. Evaristus") },
  { monthDay: "10-28", celebration: feast("Sts. Simon & Jude") },
  { monthDay: "11-02", celebration: feast("Commemoration of All Souls") },
  { monthDay: "11-04", celebration: feast("St. Charles Borromeo") },
  { monthDay: "11-08", celebration: feast("Four Holy Crowned Martyrs") },
  { monthDay: "11-09", celebration: feast("Dedication of the Archbasilica of Our Holy Savior") },
  { monthDay: "11-10", celebration: feast("St. Andrew Avellino") },
  { monthDay: "11-11", celebration: feast("St. Martin of Tours") },
  { monthDay: "11-12", celebration: feast("St. Martin I") },
  { monthDay: "11-13", celebration: feast("St. Didacus") },
  { monthDay: "11-14", celebration: feast("St. Josaphat") },
  { monthDay: "11-15", celebration: feast("St. Albert the Great") },
  { monthDay: "11-16", celebration: feast("St. Gertrude the Great") },
  { monthDay: "11-17", celebration: feast("St. Gregory the Wonderworker") },
  { monthDay: "11-18", celebration: feast("Dedication of the Basilicas of Sts. Peter & Paul") },
  { monthDay: "11-19", celebration: feast("St. Elizabeth of Hungary") },
  { monthDay: "11-20", celebration: feast("St. Felix of Valois") },
  { monthDay: "11-21", celebration: feast("Presentation of the Blessed Virgin Mary") },
  { monthDay: "11-22", celebration: feast("St. Cecilia") },
  { monthDay: "11-23", celebration: feast("St. Clement I") },
  { monthDay: "11-24", celebration: feast("St. John of the Cross") },
  { monthDay: "11-25", celebration: feast("St. Catherine of Alexandria") },
  { monthDay: "11-26", celebration: feast("St. Sylvester") },
  { monthDay: "11-29", celebration: feast("St. Saturninus") },
  { monthDay: "11-30", celebration: feast("St. Andrew") },
  { monthDay: "12-02", celebration: feast("St. Vivian") },
  { monthDay: "12-03", celebration: feast("St. Francis Xavier") },
  { monthDay: "12-04", celebration: feast("St. Peter Chrysologus") },
  { monthDay: "12-05", celebration: feast("St. Sabbas") },
  { monthDay: "12-06", celebration: feast("St. Nicholas") },
  { monthDay: "12-07", celebration: feast("St. Ambrose") },
  { monthDay: "12-10", celebration: feast("St. Melchiades") },
  { monthDay: "12-11", celebration: feast("St. Damasus I") },
  { monthDay: "12-13", celebration: feast("St. Lucy") },
  { monthDay: "12-16", celebration: feast("St. Eusebius") },
  { monthDay: "12-21", celebration: feast("St. Thomas") },
  { monthDay: "12-26", celebration: feast("St. Stephen") },
  { monthDay: "12-27", celebration: feast("St. John the Evangelist") },
  { monthDay: "12-28", celebration: feast("Holy Innocents") },
  { monthDay: "12-29", celebration: feast("St. Thomas Becket") },
  { monthDay: "12-31", celebration: feast("St. Silvester") },
];

export function findSaintOfTheDay1962(monthDay: string): Celebration | null {
  const match = saintsSeed.find((entry) => entry.monthDay === monthDay);
  return match ? match.celebration : null;
}
